### ISSUE TITLE
Displaying messages on an OLED rather than Serial window

### ISSUE THREAD

**Issue by rlbruderick** [aster94/Keyword-Protocol-2000#10]
This is a great tool!  Thank you for publishing this!  I'm planning to use this on my '06 Ninja 6R.
I've made a portable ESP32 device with an OLED display for tapping the K-line.  I want to adapt the library to allow messages on my OLED instead of on the computer's Serial window, which you do with the "_debug->print(" lines.  My 1.3" OLED uses the library U8g2lib, which is great.  I'm not fully confident that I'll code this change well, but I'm willing to try anything.  Have you considered any message display alternatives to the Serial window?

**Comment by aster94** [comment]
Hi, feel free to use the library but please do not code nothing about display into it
