### ISSUE TITLE
Arduino Mega Tx and Rx port

### ISSUE THREAD

**Issue by verygoodguy** [aster94/Keyword-Protocol-2000#15]
Hi,
I have an Arduino Mega 2560 R3. I'm having issues to setup TX and RX ports. Could you tell me port numbers?

**Comment by aster94** [comment]
please @verygoodguy use the arduino forum, github isn't made to open a issue any time you have a doubt

**Comment by verygoodguy** [comment]
"Issues" are made for asking. I'm sorry for not understand your scripts. Open source is focus on reuse code and projects. Your code  is a little bit messy but has intetesting ideas and needs upgrades but is quyte good for an amateur developer.
