### ISSUE TITLE
Can it be used in cars?

### ISSUE THREAD

**Issue by Zi-x** [aster94/Keyword-Protocol-2000#19]
Hi
My car is Suzuki, which uses K-line to obtain diagnostic data. Can this library only work on motorbike? Are the PID commands of cars and motorbike compatible?
There is another question. For the hardware diagram, is the VCC powered from the 16 pin of the OBD? Why should the K-line and the VCC be connected together?
![l9637_wiring](https://user-images.githubusercontent.com/47513451/189316741-78a065b4-6fb6-4aed-8d2d-03c98aab0a3d.png)

**Comment by 66zai** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you----------------------------------------------------------您的E-mail我已经收到，如果看到定会很快给您答复。

**Comment by aster94** [comment]
for the schematics of the 33660 i can't help, i use a different chip
let us know if it will work in your car

**Comment by Zi-x** [comment]
> for the schematics of the 33660 i can't help, i use a different chip
> let us know if it will work in your car

OK, I will try whether it can work in my car when the mc33960 I bought arrives. Recently, I also found an example of using K-line to read car data. If I succeed, I will tell you！
https://github.com/martinhol221/ISO14230-4-KWP

**Comment by aster94** [comment]
Thanks keep me updated so I update the code with the new PIDs and car model

Il dom 11 set 2022, 05:28 Zi-x ***@***.***> ha scritto:
