### ISSUE TITLE
Yamaha marine f350

### ISSUE THREAD

**Issue by arezaie14** [aster94/Keyword-Protocol-2000#4]
Hi, Can we use this to diagnostic Yamaha f350 marine motor engine?

**Comment by aster94** [comment]
hi, sorry but I never had a yamaha ECU under my hands so the library is not ready for yamaha

**Comment by arezaie14** [comment]
Thank you for reply

**Comment by aster94** [comment]
hi @arezaie14 did you discovered if your f350 uses the KWP2000 protocol?
