### ISSUE TITLE
Connecting with Yamaha ECU

### ISSUE THREAD

**Issue by vaz83** [aster94/Keyword-Protocol-2000#7]
Hello I am trying to connect to a Yamaha YXZ 1000R ECU but so far no success. Is there any way you can help me ?

**Comment by KishCom** [comment]
I'm in the same boat, I've got a YZF-R3. Taking a look at the source, it looks like [this library is missing the commands required to interface with the Yamaha ECU](https://github.com/aster94/Keyword-Protocol-2000/blob/master/src/ISO.h#L140). I've been hunting around the internet for more information without much luck.

**Comment by aster94** [comment]
if you can find the sequence which should be sent I can help you

**Comment by vaz83** [comment]
> if you can find the sequence which should be sent I can help you

Hi, the problem is that i don't know where to search for it :(

**Comment by KishCom** [comment]
> find the sequence

That's the problem. :smile: 

The YDS tool and serial protocol that actually interfaces with our bikes is very proprietary. Based on KWP2000 but ... not. Before trying with this project I tried with a couple ELM327 devices with no luck.

**Comment by vaz83** [comment]
I am a personal friend of Camelia Liparoti, i already texted her on whatsapp to see if she can put me to speak with someone related with the YDS protocol, but i am still waiting for an answer

**Comment by vaz83** [comment]
> > find the sequence
> 
> That's the problem. 😄
> 
> The YDS tool and serial protocol that actually interfaces with our bikes is very proprietary. Based on KWP2000 but ... not. Before trying with this project I tried with a couple ELM327 devices with no luck.

I was thinking, how about trying to reverse engineer the Yamaha Software? I can have acess to the software easily, the yamaha dealer is my friend, he has the computer and cables

**Comment by aster94** [comment]
> I am a personal friend of Camelia Liparoti, i already texted her on whatsapp to see if she can put me to speak with someone related with the YDS protocol, but i am still waiting for an answer

very unlikely that yamaha would provide these data

> I was thinking, how about trying to reverse engineer the Yamaha Software? I can have acess to the software easily, the yamaha dealer is my friend, he has the computer and cables

this is easier

**Comment by vaz83** [comment]
> > I am a personal friend of Camelia Liparoti, i already texted her on whatsapp to see if she can put me to speak with someone related with the YDS protocol, but i am still waiting for an answer
> 
> very unlikely that yamaha would provide these data
> 
> > I was thinking, how about trying to reverse engineer the Yamaha Software? I can have acess to the software easily, the yamaha dealer is my friend, he has the computer and cables
> 
> this is easier

i can pick the computer and cables from them tomorrow, is there any way you can help me with this? I can give remote access if necessary

**Comment by aster94** [comment]
@vaz83 unfortunately I don't have enough time to help,

first of all you need a logic analyzer (saleae makes some good one, which you can find on amazon/aliexpress as counterfait), you should send me a picture of the cable you are going to use. I think we just need to capture one cable the K-line

**Comment by BE514** [comment]
YXZ1000 should be CAN not Kline,

**Comment by KishCom** [comment]
> YXZ1000 should be CAN not Kline,

Found out my 2018 YZF-R3 is also CAN not Kline. Looks like newer or fancier bikes are CAN-BUS.
